# -*- coding: utf-8 -*-
"""smart_profile_builder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DnYdvWsrwP9RKtb3Pp1OcAiX-9fTMmke
"""

# Smart Profile Builder for Internship Applications
#Pseudocode
#start
# ask user for input ie fullname, age, email and interest
# ensure the user enters numbers only
# remove white spaces from the input, make email lowercase, capitalize the first letter of each name, split the interests into a list and remove whitespaces
# remove duplicates and sort the list alphabetically
# determine age group using the parameters given
# Display name in reversed and uppercased using string methods
# display age groups
# show number of interests
# Show the first and last interests
# Sort the interests and display
# add eligibility for the internship
# ask if the user wants to add another input, if yes, repeat the process
# If not, acknowledge the user and end the program
# stop



while True:
    full_name = input("Enter your full name: ")
    age_input = input("Enter your age: ")
    email = input("Enter your email address: ")
    interests_input = input("Enter 3 interests (comma-separated): ")

    if not age_input.isdigit():
        print("Invalid age. Please enter numbers only.")
        continue
    age = int(age_input)

    full_name = full_name.strip().title()
    email = email.strip().lower()

    interests = interests_input.split(",")
    cleaned_interests = []

    for item in interests:
        item = item.strip().title()
        if item not in cleaned_interests:
            cleaned_interests.append(item)

    cleaned_interests.sort()

    if age >= 13 and age <= 17:
        age_group = "Teen"
    elif age >= 18 and age <= 25:
        age_group = "Young Adult"
    else:
        age_group = "Other"

    print("Profile Summary")
    reversed_name = full_name[::-1].upper()
    print(f"Name (reversed & uppercase): {reversed_name}")

    print(f"Age Group: {age_group}")
    print("Number of Interests: {}".format(len(cleaned_interests)))

    if len(cleaned_interests) > 0:
        print("First Interest: {}".format(cleaned_interests[0]))
        print("Last Interest: {}".format(cleaned_interests[-1]))

    print("Sorted Interests: {}".format(", ".join(cleaned_interests)))

    if age >= 18:
        print("You are eligible for internship.")
    else:
        print("You are not eligible for internship yet.")

    again = input("\nDo you want to enter another profile? (yes/no): ").strip().lower()
    if again != "yes":
        print("Thank you for using the Smart Profile Builder.")
        break